//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HWA.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διεύθυνση.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το ραντεβού σας έχει σταλεί.
        /// </summary>
        internal static string appoinment_result {
            get {
                return ResourceManager.GetString("appoinment_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κάτι πήγε στραβά. Η φόρμα δεν στάλθηκε.
        /// </summary>
        internal static string appoinment_result_error {
            get {
                return ResourceManager.GetString("appoinment_result_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιοχή.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Άκυρο.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγνωστικό Κέντρο.
        /// </summary>
        internal static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ραντεβού σε Διαγνωστικό Κέντρο.
        /// </summary>
        internal static string centerappointment {
            get {
                return ResourceManager.GetString("centerappointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkup.
        /// </summary>
        internal static string checkup {
            get {
                return ResourceManager.GetString("checkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξτε.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλογή αρχείου.
        /// </summary>
        internal static string choosefile {
            get {
                return ResourceManager.GetString("choosefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πόλη.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κλινική.
        /// </summary>
        internal static string clinic {
            get {
                return ResourceManager.GetString("clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός Συμβολαίου.
        /// </summary>
        internal static string contractNo {
            get {
                return ResourceManager.GetString("contractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός πελάτη.
        /// </summary>
        internal static string customercode {
            get {
                return ResourceManager.GetString("customercode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημερομηνία.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ραντεβού με γιατρό.
        /// </summary>
        internal static string docappointment {
            get {
                return ResourceManager.GetString("docappointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είσοδος.
        /// </summary>
        internal static string entry {
            get {
                return ResourceManager.GetString("entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναγγελία νοσηλείας.
        /// </summary>
        internal static string hospitalization {
            get {
                return ResourceManager.GetString("hospitalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σύνδεση.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποσύνδεση.
        /// </summary>
        internal static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λίστα Δικτύου.
        /// </summary>
        internal static string netlist {
            get {
                return ResourceManager.GetString("netlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εναλλακτική ημερομηνία.
        /// </summary>
        internal static string otherdate {
            get {
                return ResourceManager.GetString("otherdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πακέτο Κάλυψης.
        /// </summary>
        internal static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επείγον περιστατικό.
        /// </summary>
        internal static string panicbtn {
            get {
                return ResourceManager.GetString("panicbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τηλέφωνο.
        /// </summary>
        internal static string phoneNo {
            get {
                return ResourceManager.GetString("phoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προτιμώμενη ώρα.
        /// </summary>
        internal static string preftime {
            get {
                return ResourceManager.GetString("preftime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναζήτηση.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ειδικότητα.
        /// </summary>
        internal static string specialty {
            get {
                return ResourceManager.GetString("specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υποβολή.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
    }
}
